host: login.salesforce.com
client_secret: 3361949083019338033
client_id: 3MVG9xOCXq4ID1uEeNTI_GVd2cB9zN6pi8DJJuE0ZC7YOGbhQnWep0Sk1XyjjYj.DVr2dopiifgbxgu.FlS8L
sobject_module: SFDC_Models
version: 23.0
debugging: true
username: thesilvercloud2014@gmail.com
password: Hackathon2014Brf4sVX9U09ooty81FYIECIM
